In [1]:
#1.
def maximum():
  l=[]
  for i in range(3):
    n1=int(input('enter a number:'))
    l.append(n1)
  return((max(l)))
maxi=maximum()
print(maxi)

enter a number:4
enter a number:5
enter a number:8
8


In [2]:
#2.
from math import*
def areacircle():
  r=int(input('enter radius:'))
  return(pi*r**2)
area_c=areacircle()
print(area_c)

enter radius:2
12.566370614359172


In [3]:
#3.
def prime_number():
  n=int(input('Enter the number:'))
  if n==2:
    return('prime numer')
  else:
    for i in range(2,n):
      if n%i==0:
        return('not prime number')
      else:
        return('prime number')

pr=prime_number()
print(pr)



Enter the number:11
prime number


In [4]:
#4.
def pal():
  sample=input('Enter:')
  if sample==sample[::-1]:
    return('Palindrome')
  else:
    return('not a Palindrome')
palind=pal()
print(palind)

Enter:4004
Palindrome


In [5]:
palind=pal()
print(palind)

Enter:malayalam
Palindrome


In [6]:
#5.
def list_sum():
  list_2=[]
  n=int(input('Enter number of elements in the list:'))
  for i in range(n):
    x1=int(input('Enter number:'))
    list_2.append(x1)
  return(sum(list_2))

su=list_sum()
print(su)


Enter number of elements in the list:3
Enter number:5
Enter number:3
Enter number:8
16


In [7]:
#6.
def average():
   list_3=[]
   n1=int(input('Enter number of elements in the list:'))
   for i in range(n1):
    x2=int(input('Enter number:'))
    list_3.append(x2)
   return((sum(list_3))/n1)

avg=average()
print(avg)


Enter number of elements in the list:3
Enter number:2
Enter number:3
Enter number:4
3.0


In [8]:
#7.
import heapq
def kth_largest():
  list_4=[]
  k=int(input('Enter k:'))
  m=int(input('Enter no of elements:'))
  for i in range(m):
    y=int(input('Enter number:'))
    list_4.append(y)
  if k>len(list_4):
    return('none')
  kth_largest_elements=heapq.nlargest(k,list_4)
  return kth_largest_elements[-1]

lar=kth_largest()
print(lar)




Enter k:2
Enter no of elements:3
Enter number:1
Enter number:3
Enter number:4
3


In [9]:
#8.
def sum_digits(a):
  if a<10 and a>0:
    return a
  else:
    return a%10+sum_digits(a//10)

def inp():
  a=int(input('Enter number:'))
  sd=sum_digits(a)
  print(sd)

inp()


Enter number:45
9


In [11]:
#9.

def power_nmbr(base, exponent):
    if exponent == 0:
        return 1
    else:
        return base * power_nmbr(base, exponent - 1)

def main():
    base = int(input('Enter the base number: '))
    exponent = int(input('Enter the exponent: '))
    result = power_nmbr(base, exponent)
    print(f"{base} raised to the power of {exponent} is {result}")

main()


Enter the base number: 2
Enter the exponent: 3
2 raised to the power of 3 is 8


In [12]:
#10.
def gcd_recursive(a, b):
    if b == 0:
        return a
    else:
        return gcd_recursive(b, a % b)

result = gcd_recursive(48, 18)
print(result)


6


In [13]:
#11.
import numpy as np
arr1=np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
#12.
import numpy as np
arr2=np.arange(1,10).reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
#13.
import numpy as np
id_m=np.eye(3,3)
print(id_m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#14.
import numpy as np
random_array = np.random.randint(0, 10, size=5)
print(random_array)
mean_arr=np.mean(random_array)
std_dev=np.std(random_array)
print(mean_arr)
print(std_dev)

[2 8 7 1 8]
5.2
3.059411708155671


In [28]:
#15.
arr5 = np.arange(10, 21)
first_five_elements = arr5[:5]
print(arr5)
print(first_five_elements)

[10 11 12 13 14 15 16 17 18 19 20]
[10 11 12 13 14]


In [30]:
#16.
arr6= np.arange(1, 17).reshape(4, 4)
second_row = arr6[1, :]
print(arr6)
print(second_row)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[5 6 7 8]


In [31]:
#17.
array1 = np.arange(1, 6)
array2 = np.arange(6, 11)
result_array = array1 + array2
print("First Array:")
print(array1)
print("Second Array:")
print(array2)
print("Element-wise addition:")
print(result_array)


First Array:
[1 2 3 4 5]
Second Array:
[ 6  7  8  9 10]
Element-wise addition:
[ 7  9 11 13 15]


In [33]:
#18.
np.random.seed(1)
random_array_10 = np.random.rand(10)
random_array_10[random_array_10 < 0.5] = 0
print("Random Array:")
print(random_array_10)


Random Array:
[0.         0.72032449 0.         0.         0.         0.
 0.         0.         0.         0.53881673]
